name: Upload to Azure Blob Storage
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  setup:
    name: Setup & Upload
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Delete all lithology patterns in blob storage
        run: |
          az storage blob delete-batch \
          --account-name ${{ secrets.AZ_STORAGE_ACCOUNT_NAME }} \
          --source lithology-patterns

      - name: Upload lithology patterns assets
        working-directory: ./assets
        run: |
          az storage blob upload-batch \
          --account-name ${{ secrets.AZ_STORAGE_ACCOUNT_NAME }} \
          --source ./svg \
          --destination lithology-patterns

      - run: az logout
        if: ${{ always() }}